### ISSUE TITLE
process.py crashes when reports contain internationalized domain names

### ISSUE THREAD

**Issue by stiiin** [poorting/internet.nl_batch_scripts#3]
# Problem

Our scan happens to include an internationalized domain name. In the scan report, this domain name is included as a field name of the object under the field `domain`, spelled as something along the lines of `"ourdom\u00e1in.example.com"`. When we try to process these files, though, we get the following result:

```console output
(venv) ...\batch-scan> python process.py measurements output-20220317.xlsx
Processed 372 web measurements from 1 files
Processed 372 mail measurements from 1 files
Creating output-20220317.xlsx file
        creating sheet web
Traceback (most recent call last):
  File "...\batch-scan\process.py", line 420, in <module>
    main()
  File "...\batch-scan\process.py", line 392, in main
    df = pd.read_csv(tmpfilename)
  File "...\batch-scan\venv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "...\batch-scan\venv\lib\site-packages\pandas\io\parsers\readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "...\batch-scan\venv\lib\site-packages\pandas\io\parsers\readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
 File "...\batch-scan\venv\lib\site-packages\pandas\io\parsers\readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "...\batch-scan\venv\lib\site-packages\pandas\io\parsers\readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "...\batch-scan\venv\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas\_libs\parsers.pyx", line 542, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 642, in pandas._libs.parsers.TextReader._get_header
  File "pandas\_libs\parsers.pyx", line 843, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas\_libs\parsers.pyx", line 1917, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 51382: invalid continuation byte
```

# Cause

The intermediate CSV is being written and read under different character encodings. In my case, it's probably latin-1 for writing, and utf-8 for reading.

All across process.py, files are being written using only mode `'w'`. In Python 3, that means that the file is opened in text mode, and since no encoding is specified, this encoding is locale-dependent.

# Solution

The solution would be to always be explicit about the used encoding whenever temporary files are used, not only when they are written, but also when they're loaded (pandas uses `open()` as well). Since DuckDB only supports UTF-8, the encoding must be UTF-8.

Submitting the batch using the A-label of the IDN doesn't help: the field name in the `domain` object in the downloaded report will contain the U-label anyway.

**Comment by poorting** [comment]
I couldn't reproduce your problem (on linux or mac) no matter what I tried, even if I set locale to something not supporting unicode (and I see the unicode characters as 'escaped' representation using cat) nothing crashes. Do you use Windows by any chance?
I did add encoding='utf-8' for every temp file, but checking whether that solves your issue is something I can't do since I can't reproduce the issue. 
Then again: if you are working with IDN, setting your locale to something unicodey is probably advisable anyway.

**Comment by stiiin** [comment]
Correct, I use Windows. I also didn't manage to reproduce the issue on Linux yet, even when I manage to convince Python that there's a different preferred encoding than UTF-8. I'll experiment a bit more to get a reproducible case.

**Comment by poorting** [comment]
Cheers, much appreciated!
Please keep me posted and let me know if I can help.

**Comment by stiiin** [comment]
The [commit where you added `encoding='utf-8'`](https://github.com/poorting/internet.nl_batch_scripts/commit/b4f0c120f3ee7014583fb2eff9a7c2130ba0d6a2) fixed the issue (in particular the change on line 390).

It appears that [pandas' `read_csv` always defaults to `"utf-8"` when no `encoding` is provided](https://github.com/pandas-dev/pandas/blob/v1.4.1/pandas/io/common.py#L657), while Python's `open` uses `locale.getpreferredencoding(False)`. These match up on modern Linux distributions by default, but mismatch on Windows (the locale encoding is CP1252), which completely explains the crashes. When forcing UTF-8 mode (e.g. `python3 -X utf8 process.py measurements out.xlsx`), the script succeeds on both Debian Bullseye and Windows 11.

Reproducing the case before that commit was possible using the following fake report in the folder `measurements`:

```json
{
  "api_version": "2.0.0",
  "request": {
    "name": "test",
    "submit_date": "1972-01-01T00:00:00.0+00:00",
    "finished_date": "1972-01-01T00:00:00.0+00:00",
    "request_type": "web",
    "status": "done"
  },
  "domains": {
    "subdom\u00e1in.example.com": {
      "status": "failed",
      "report": {"url": "https://example.com/"},
      "scoring": {"percentage": 0},
      "results": {
        "categories": {},
        "tests": {},
        "custom": {}
      }
    }
  }
}
```

To reproduce it on Debian Bullseye, I had to take the following steps:

* Make sure that the file `/usr/local/share/i18n/SUPPORTED` contains the line `en_US.CP1252 CP1252`.
* Add `en_US.CP1252` to the locales to generate (`/etc/locale.gen`).
* Run `/usr/sbin/locale-gen` (or use `dpkg-reconfigure`, [as explained on Ask Ubuntu](https://askubuntu.com/a/1120386)).
* Run `LC_ALL=en_US.CP1252 python3 process.py measurements out.xlsx`.

On Windows, `python process.py measurements out.xlsx` was sufficient.
